### ISSUE TITLE
python-multipart 0.0.13 was yanked

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/python-multipart-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

https://pypi.org/project/python-multipart/0.0.13/

https://github.com/Kludex/python-multipart/pull/166#issuecomment-2425215315

### Installed packages

Not relavant

### Environment info

not relavant

**Comment by carlodri** [comment]
Thanks for the report, should be tackled with https://github.com/conda-forge/admin-requests/pull/1111

**Comment by carlodri** [comment]
ok, PR was merged. This should be fixed as soon as the CDN updates in a couple of hours.
